---
- name: Pull dotfiles
  git:
    dest: "{{ home_dir }}"
    repo: "https://github.com/H3xaT0m/dotfiles.git"
    track_submodules: yes

- name: check for existing dotfiles
  stat:
    path: "{{ home_dir }}/{{ item }}"
  register: "{{ item }}_exists"
  with_items: "{{ dotfile_list }}"

- name: symlink dotfiles
  file:
    src: "{{ home_dir }}/dotfiles/{{ item }}"
    dest: "{{ home_dir }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  when: not "{{ item }}".stat.exists

