---
- hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:
  - name: Install default packages
    pacman:
      update_cache: yes
      upgrade: yes
      name: "{{ default_packages }}"
      state: latest

  - name: Test running
    command: hostname

