---
- hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: tasks/package_install.yml
    - import_tasks: tasks/dir_structure.yml
    - import_tasks: tasks/dotfiles.yml

