---
- name: Pull dotfiles
  git:
    dest: "{{ dotfiles_dir }}"
    repo: "{{ dotfiles_repo }}"
    force: yes
    track_submodules: yes

- name: find dotfiles
  find:
    paths: "{{ dotfiles_dir }}"
    excludes: '.gitmodules,.gitignore,.vimrc,.zshrc,.tmux.conf'
    hidden: yes
  register: dotfiles_found

- name: find non-symlink dotfiles
  find:
    path: "{{ home_dir }}/{{ item.path.split('/')[-1] }}"
    hidden: yes
  with_items: "{{ dotfiles_found.files }}"
  register: dotfiles_non_symlink

- name: delete old dotfiles
  file:
    path: "{{ home_dir }}/{{ item.path.split('/')[-1] }}"
    state: absent
  with_items: "{{ dotfiles_non_symlink.files }}"

- name: symlink dotfiles
  file:
    src: "{{ item.path }}"
    dest: "{{ home_dir }}/{{ item.path.split('/')[-1] }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  with_items: "{{ dotfiles_found.files }}"

# Vim Section
- name: create .vim dirs
  file:
    path: "{{ vim_plugin_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: symlink .vimrc
  file:
    src: "{{ dotfiles_dir }}/.vimrc"
    dest: "{{ vim_dir }}/vimrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link

- name: pull vim plugins
  git:
    dest: "{{ vim_plugin_dir }}/{{ item.split('/')[-1].split('.')[0] }}"
    repo: "{{ item }}"
    force: yes
  with_items: "{{ vim_plugins }}"

- name: create vim.local
  file:
    path: "{{ vim_dir }}/vimrc.local"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

# Zsh Section
- name: create .zsh dir
  file:
    path: "{{ zsh_plugin_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: symlink .zshrc
  file:
    src: "{{ dotfiles_dir }}/.zshrc"
    dest: "{{ zsh_dir }}/.zshrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link

- name: pull zsh plugins
  git:
    dest: "{{ zsh_plugin_dir }}/{{ item.split('/')[-1].split('.')[0] }}"
    repo: "{{ item }}"
    force: yes
  with_items: "{{ zsh_plugins }}"

- name: make zsh default
  user:
    name: "{{ ansible_user }}"
    shell: "{{ default_shell }}"

# Tmux Section
- name: create .tmux dir
  file:
    path: "{{ tmux_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: symlink .tmux.conf
  file:
    src: "{{ dotfiles_dir }}/.tmux.conf"
    dest: "{{ tmux_dir }}/.tmux.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link

- name: create .tmux.conf.local
  file:
    path: "{{ tmux_dir }}/.tmux.conf.local"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

# Display Section
- name: add HiDPI section if necessary
  blockinfile:
    path: "{{ home_dir }}/.Xresources"
    block: |
      Xft.dpi: 192
      Xft.autohint: 0
      Xft.lcdfilter:  lcddefault
      Xft.hintstyle:  hintfull
      Xft.hinting: 1
      Xft.antialias: 1
      Xft.rgba: rgb
  when: hidpi|bool

# Local Config File Section
- name: create .gitconfig.local
  file:
    path: "{{ home_dir }}/.gitconfig.local"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

