---
- name: Pull dotfiles
  git:
    dest: "{{ dotfiles_dir }}"
    repo: "{{ dotfiles_repo }}"
    force: yes
    track_submodules: yes

- name: find dotfiles
  find:
    paths: "{{ dotfiles_dir }}"
    excludes: '.gitmodules,.gitignore,.vimrc'
    hidden: yes
  register: dotfiles_found

- name: backup dotfiles
  file:
    path: "{{ home_dir }}/{{ item.path.split('/')[-1] | lower }}"
    state: absent
  with_items: "{{ dotfiles_found.files }}"

- name: symlink dotfiles
  file:
    src: "{{ item.path }}"
    dest: "{{ home_dir }}/{{ item.path.split('/')[-1] | lower }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  with_items: "{{ dotfiles_found.files }}"

# Vim Section
- name: create .vim dirs
  file:
    path: "{{ vim_plugin_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: symlink .vimrc
  file:
    src: "{{ dotfiles_dir }}/.vimrc"
    dest: "{{ vim_dir }}/.vimrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link

- name: pull vim plugins
  git:
    dest: "{{ vim_plugin_dir }}/{{ item.path.split('/')[-1].split('.')[0] | lower }}"
    repo: "{{ item }}"
    force: yes
  with_items: "{{ vim_plugins }}"

# Zsh Section
- name: create .zsh dirs
  file:
    path: "{{ zsh_plugin_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: symlink .zshrc
  file:
    src: "{{ dotfiles_dir }}/.zshrc"
    dest: "{{ zsh_dir }}/.zshrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link

- name: pull zsh plugins
  git:
    dest: "{{ zsh_plugin_dir }}/{{ item.path.split('/')[-1].split('.')[0] | lower }}"
    repo: "{{ item }}"
    force: yes
  with_items: "{{ zsh_plugins }}"

