---
- name: update whole system
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install default packages
  pacman:
    update_cache: yes
    name: "{{ default_packages }}"
    state: latest

